
/*
 * This source file was generated by the Gradle 'init' task
*/
package graphTheory;

import java.io.IOException;

import graphTheory.graph.Graph;
import graphTheory.reader.Reader;
import graphTheory.successiveShortestPath.SSPSingleSource;
import graphTheory.successiveShortestPath.SuccessiveShortestPath;

public class App {
    public static void main(String[] args) {
        try {
            Graph g = Reader.readFromFile("input.in");
            SuccessiveShortestPath ssp = new SSPSingleSource(g);
            ssp.run();

            System.out.println(ssp);

        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
