
/*
 * This source file was generated by the Gradle 'init' task
*/
package graphTheory;

import java.io.IOException;

import graphTheory.graph.Graph;
import graphTheory.reader.Reader;
import graphTheory.successiveShortestPath.SSPSingleSource;
import graphTheory.successiveShortestPath.SuccessiveShortestPath;

public class App {
    public static void main(String[] args) {
        try {
            String[] inputFiles = new String[] {
                    "input1.in",
                    "input2.in",
                    "input3.in",
                    "input4.in",
                    "input5.in",
                    "input6.in",
                    "inputFail1.in", // Disconnected Graph
                    "inputFail2.in" // Insufficient Capacity Path
            };

            for (String file : inputFiles) {
                System.out.println("--------- SOLVING test " + file + " --------------");
                Graph g = Reader.readFromFile(file);
                SuccessiveShortestPath ssp = new SSPSingleSource(g);
                ssp.run();

                // System.out.println(ssp);
                System.out.println(ssp.solutionToString());
            }

        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
